spring:
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: "HTML"
    encoding: "UTF-8"
    cache: false

feature-flags:
  include-path-pattern:
    - "/**"
  features:
    experimental: true
    development: false
